post http://localhost:3000/login
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}
###
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYzMzM5Mjc1fQ.l5oOp6NkekyMP43V_HikW83JN2wz0NVptUL3Vs4sZy0

###
GET http://localhost:3000/states/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYzMzM5Mjc1fQ.l5oOp6NkekyMP43V_HikW83JN2wz0NVptUL3Vs4sZy0


###
POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYzMzM5Mjc1fQ.l5oOp6NkekyMP43V_HikW83JN2wz0NVptUL3Vs4sZy0


###
GET http://localhost:3000/districts/322/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYzMzM5Mjc1fQ.l5oOp6NkekyMP43V_HikW83JN2wz0NVptUL3Vs4sZy0


###
DELETE http://localhost:3000/districts/321/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYzMzM5Mjc1fQ.l5oOp6NkekyMP43V_HikW83JN2wz0NVptUL3Vs4sZy0

###
PUT http://localhost:3000/districts/321/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYzMzM5Mjc1fQ.l5oOp6NkekyMP43V_HikW83JN2wz0NVptUL3Vs4sZy0


###
GET http://localhost:3000/states/11/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjYzMzM5Mjc1fQ.l5oOp6NkekyMP43V_HikW83JN2wz0NVptUL3Vs4sZy0
